#! /bin/csh -f

#
# Shut down entire system
#

# remove crontab and kill the auto-restarter

remove_crontab
kill_auto_restart

procmap_list_kill -proc_list $PROJ_DIR/control/proc_list

# kill the server manager so that it does not restart processes
# which have been killed already.
# Also kill DsFCopyServer and DsSpdbServer so new data does
# not arrive after stopping the system.

kill_DsServers
kill_SymprodServers

# kill all processes

killall_processes

# remove shared memory segments

ipcrm_linux

